<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Close</name>
   <tag></tag>
   <elementGuidId>26f770ed-c90b-45aa-9c7f-f673358c25ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//account-setting-popup//i[contains(@class,'icon-close')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
